HEYGEN_DEFAULT_ELEVEN_LABS_MODEL = "eleven_multilingual_v2"
HEYGEN_DEFAULT_ELEVEN_LABS_SIMILARITY_BOOST = 0.75
HEYGEN_DEFAULT_ELEVEN_LABS_STABILITY = 0.75
HEYGEN_DEFAULT_ELEVEN_LABS_STYLE = 0.0

HEYGEN_DEFAULT_TEXT_VOICE_SPEED = 1.0
HEYGEN_DEFAULT_TEXT_VOICE_EMOTION = "Excited"
HEYGEN_DEFAULT_TEXT_VOICE_LOCALE = "es-ES"
HEYGEN_DEFAULT_TEXT_VOICE_TYPE = "text"

HEYGEN_DEFAULT_SILENCE_VOICE_TYPE = "silence"
